In [23]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
promptcloudhq_flipkart_products_path = kagglehub.dataset_download('PromptCloudHQ/flipkart-products')

print('Data source import complete.')

Using Colab cache for faster access to the 'flipkart-products' dataset.
Data source import complete.

In [24]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
# print(os.listdir("../input")) # Commented out the problematic line

# Instead, list the contents of the downloaded dataset path
print(os.listdir(promptcloudhq_flipkart_products_path))

# Any results you write to the current directory are saved as output.

['flipkart_com-ecommerce_sample.csv', '.nfs000000005c65e5d700000096']

In [25]:
df=pd.read_csv(os.path.join(promptcloudhq_flipkart_products_path, 'flipkart_com-ecommerce_sample.csv'))

In [26]:
df.head()

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [27]:
import re
import nltk
from nltk import pos_tag, word_tokenize, PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
wordnet_lemmatizr=WordNetLemmatizer()

In [28]:
from termcolor import colored

In [29]:
def clean_product_type(dataframe):
    document=list(dataframe['product_category_tree'])
    product_types=[re.findall(r'\"(.*?)\"', sentence) for sentence in document]
    product_types=[' '.join(listed_items) for listed_items in product_types]
    return(product_types)

In [30]:
def clean_categories(dataframe):
    document=list(dataframe['product_category_tree'].values)
    categories=[re.findall(r'name=(.*?)}',sentence) for sentence in document]
    categories=[' '.join(word) for word in categories]
    return(categories)

In [31]:
def special_characters_cleaning(document):
    sentences=[]
    for sentence in document:
        sentences.append(re.sub('[^a-zA-Z0-9\n\.]',' ',str(sentence)))
    return(sentences)

<>:4: SyntaxWarning: invalid escape sequence '\.'
<>:4: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_5783/208882036.py:4: SyntaxWarning: invalid escape sequence '\.'
  sentences.append(re.sub('[^a-zA-Z0-9\n\.]',' ',str(sentence)))

In [32]:
def lemmetize_document(document):
    sentences=[]
    for sentence in document:
        word=[wordnet_lemmatizer.lemmatize(word) for word in word_tokenize(sentence)]
        sentences.append(' '.join(words))
    return(sentences)

In [33]:
def categories_extraction(dataframe):
    categories=[word for item in dataframe['categories'] for word in item.split()]
    categories=list(set(categories))
    return(categories)

In [34]:
def save_categories(dataframe):
    pass

In [35]:
def pre_processing_document(document):
    document=special_characters_cleaning(document)
    document=lemmetize_document(document)
    document=[sentence.title() for sentence in document]
    return(document)

In [36]:
def extract_categories_from_description(document,categories):
    extracted_categories=[]
    for sentence in document:
        extracted_categories.append(' '.join(set(categories).intersection(set(word_tokenize(sentence)))))
        return(extracted_categories)

In [37]:
lemmetize= WordNetLemmatizer()
stemmer=PorterStemmer()

In [38]:
df["products"]=clean_product_type(df)

In [39]:
df["categories"]=clean_categories(df)

In [40]:
categories= list(set(df['product_category_tree'].values))
categories= [item.split() for item in df['product_category_tree']]
categories= [word.lower() for listed_item in categories for word in listed_item]
categories= list(set(categories))

In [41]:
df

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications,products,categories
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ...","Clothing >> Women's Clothing >> Lingerie, Slee...",
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati...",Furniture >> Living Room Furniture >> Sofa Bed...,
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""...",Footwear >> Women's Footwear >> Ballerinas >> ...,
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ...","Clothing >> Women's Clothing >> Lingerie, Slee...",
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",...",Pet Supplies >> Grooming >> Skin & Coat Care >...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,http://www.flipkart.com/walldesign-small-vinyl...,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7KFJAKSTDY9G,1500.0,730.0,"[""http://img6a.flixcart.com/image/wall-decorat...",False,Buy WallDesign Small Vinyl Sticker for Rs.730 ...,No rating available,No rating available,WallDesign,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,http://www.flipkart.com/wallmantra-large-vinyl...,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE9F5URNQGJCGH,1429.0,1143.0,"[""http://img6a.flixcart.com/image/sticker/z/g/...",False,Buy Wallmantra Large Vinyl Stickers Sticker fo...,No rating available,No rating available,Wallmantra,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7VAYDKQZEBSD,1299.0,999.0,"[""http://img5a.flixcart.com/image/sticker/b/s/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE8YSVEPPCZ42Y,1499.0,1199.0,"[""http://img5a.flixcart.com/image/sticker/4/2/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE88KN9ZDSGZKY,1499.0,999.0,"[""http://img6a.flixcart.com/image/sticker/z/k/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,

In [42]:
df['detailed_description']= df['products']+ df['brand']+df['product_name']

In [43]:
df

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications,products,categories,detailed_description
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ...","Clothing >> Women's Clothing >> Lingerie, Slee...",,"Clothing >> Women's Clothing >> Lingerie, Slee..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati...",Furniture >> Living Room Furniture >> Sofa Bed...,,Furniture >> Living Room Furniture >> Sofa Bed...
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""...",Footwear >> Women's Footwear >> Ballerinas >> ...,,Footwear >> Women's Footwear >> Ballerinas >> ...
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ...","Clothing >> Women's Clothing >> Lingerie, Slee...",,"Clothing >> Women's Clothing >> Lingerie, Slee..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",...",Pet Supplies >> Grooming >> Skin & Coat Care >...,,Pet Supplies >> Grooming >> Skin & Coat Care >...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,http://www.flipkart.com/walldesign-small-vinyl...,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7KFJAKSTDY9G,1500.0,730.0,"[""http://img6a.flixcart.com/image/wall-decorat...",False,Buy WallDesign Small Vinyl Sticker for Rs.730 ...,No rating available,No rating available,WallDesign,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,,Baby Care >> Baby & Kids Gifts >> Stickers >> ...
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,http://www.flipkart.com/wallmantra-large-vinyl...,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE9F5URNQGJCGH,1429.0,1143.0,"[""http://img6a.flixcart.com/image/sticker/z/g/...",False,Buy Wallmantra Large Vinyl Stickers Sticker fo...,No rating available,No rating available,Wallmantra,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,,Baby Care >> Baby & Kids Gifts >> Stickers >> ...
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7VAYDKQZEBSD,1299.0,999.0,"[""http://img5a.flixcart.com/image/sticker/b/s/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,,Baby Care >> Baby & Kids Gifts >> Stickers >> ...
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE8YSVEPPCZ42Y,1499.0,1199.0,"[""http://img5a.flixcart.com/image/sticker/4/2/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,,Baby Care >> Baby & Kids Gifts >> Stickers >> ...
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE88KN9ZDSGZKY,1499.0,999.0,"[""http://img6a.flixcart.com/image/sticker/z/k/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ...",Baby Care >> Baby & Kids Gifts >> Stickers >> ...,,Baby Care >> Baby & Kids Gifts >> Stickers >> ...

In [44]:
document= list(df['detailed_description'].values)
document= special_characters_cleaning(document)

In [45]:
tfidf= TfidfVectorizer(stop_words= 'english', vocabulary= categories)
data= tfidf.fit_transform(document)

In [46]:
from sklearn.neighbors import NearestNeighbors
nn= NearestNeighbors(algorithm= 'brute', n_neighbors= 20).fit(data)

In [48]:
text= df[df['brand']== "FabHomeDecor"]['detailed_description'].values
result = nn.kneighbors(tfidf.transform(text))
for col in tfidf.transform(text).nonzero()[1]:
    print(tfidf.get_feature_names_out()[col], ' - ', tfidf.transform(text)[0, col])

beds  -  0.23771412515246718
bed  -  0.28650919452707707
finish  -  0.19805109200546914
sofa  -  0.5494627319447266
double  -  0.3362594739889644
furniture  -  0.31267075585498627
fabhomedecor  -  0.25687140760783667
fabric  -  0.3404245070225777
futons  -  0.25687140760783667
room  -  0.17792395156869212
living  -  0.1729910237070467
beds  -  0.23771412515246718
bed  -  0.28650919452707707
finish  -  0.19805109200546914
sofa  -  0.5494627319447266
double  -  0.3362594739889644
furniture  -  0.31267075585498627
fabhomedecor  -  0.25687140760783667
fabric  -  0.3404245070225777
futons  -  0.25687140760783667
room  -  0.17792395156869212
living  -  0.1729910237070467
beds  -  0.23771412515246718
bed  -  0.28650919452707707
finish  -  0.19805109200546914
sofa  -  0.5494627319447266
double  -  0.3362594739889644
furniture  -  0.31267075585498627
fabhomedecor  -  0.25687140760783667
fabric  -  0.3404245070225777
futons  -  0.25687140760783667
room  -  0.17792395156869212
living  -  0.1729910237070467
beds  -  0.23771412515246718
bed  -  0.28650919452707707
finish  -  0.19805109200546914
sofa  -  0.5494627319447266
double  -  0.3362594739889644
furniture  -  0.31267075585498627
fabhomedecor  -  0.25687140760783667
fabric  -  0.3404245070225777
futons  -  0.25687140760783667
room  -  0.17792395156869212
living  -  0.1729910237070467

In [49]:
for item in result[1][0]:
    print(colored(df.iloc[item]['product_category_tree'].upper(), 'blue'), ':', document[item])

["FURNITURE >> LIVING ROOM FURNITURE >> SOFA BEDS & FUTONS >> FABHOMEDECOR FABRIC DOUBLE SOFA BED (FINISH COLO..."] : Furniture    Living Room Furniture    Sofa Beds   Futons    FabHomeDecor Fabric Double Sofa Bed  Finish Colo...FabHomeDecorFabHomeDecor Fabric Double Sofa Bed
["FURNITURE >> LIVING ROOM FURNITURE >> SOFA BEDS & FUTONS >> FABHOMEDECOR FABRIC DOUBLE SOFA BED (FINISH COLO..."] : Furniture    Living Room Furniture    Sofa Beds   Futons    FabHomeDecor Fabric Double Sofa Bed  Finish Colo...FabHomeDecorFabHomeDecor Fabric Double Sofa Bed
["FURNITURE >> LIVING ROOM FURNITURE >> SOFA BEDS & FUTONS >> FABHOMEDECOR FABRIC DOUBLE SOFA BED (FINISH COLO..."] : Furniture    Living Room Furniture    Sofa Beds   Futons    FabHomeDecor Fabric Double Sofa Bed  Finish Colo...FabHomeDecorFabHomeDecor Fabric Double Sofa Bed
["FURNITURE >> LIVING ROOM FURNITURE >> SOFA BEDS & FUTONS >> FABHOMEDECOR FABRIC DOUBLE SOFA BED (FINISH COLO..."] : Furniture    Living Room Furniture    Sofa Beds   Futons    FabHomeDecor Fabric Double Sofa Bed  Finish Colo...FabHomeDecorFabHomeDecor Fabric Double Sofa Bed
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsFurnstylFurnstyl Maxwell Fabric 1 Seater Sofa
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsDurianDurian Harmony 2 Fabric 2 Seater Sofa
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsDurianDurian Fabric 3 Seater Sofa
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsDurianDurian Fabric 1 Seater Sofa
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsDurianDurian Helena Fabric 3 Seater Sofa
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsDurianDurian Fabric 2 Seater Sofa
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsDurianDurian Fabric 3 Seater Sofa
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsDurianDurian Fabric 1 Seater Sofa
["FURNITURE >> LIVING ROOM >> SOFAS & SECTIONALS"] : Furniture    Living Room    Sofas   SectionalsDurianDurian Helena Fabric 3 Seater Sofa
["CLOTHING >> WOMEN'S CLOTHING >> WESTERN WEAR >> SHIRTS, TOPS & TUNICS >> SHIRTS >> THEGUDLOOK SHIRTS"] : nan
["CLOTHING >> WOMEN'S CLOTHING >> ETHNIC WEAR >> KURTAS & KURTIS >> KURTIS >> VITALLY CLOTHING KURTIS"] : nan
["CLOTHING >> WOMEN'S CLOTHING >> WESTERN WEAR >> SHIRTS, TOPS & TUNICS >> SHIRTS >> ORANGE PLUM SHIRTS"] : nan
["CLOTHING >> WOMEN'S CLOTHING >> WESTERN WEAR >> SHIRTS, TOPS & TUNICS >> SHIRTS >> KARISHMA SHIRTS"] : nan
["CLOTHING >> WOMEN'S CLOTHING >> ETHNIC WEAR >> FABRIC >> DRESS MATERIAL >> PARISHA DRESS MATERIAL"] : nan
["CLOTHING >> WOMEN'S CLOTHING >> ETHNIC WEAR >> FABRIC >> DRESS MATERIAL >> PARISHA DRESS MATERIAL"] : nan
["CLOTHING >> WOMEN'S CLOTHING >> ETHNIC WEAR >> FABRIC >> DRESS MATERIAL >> PARISHA DRESS MATERIAL"] : nan